name: time-series-analysis
channels:
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - pandas=0.25
  - numpy=1.16.5
  - scipy=1.3.1
  - bokeh=1.3.4
  - seaborn=0.9.0
  - pip=19.2